#!/bin/bash

# Export envs from .env if needed
export $(grep -v '^#' /app/.env | xargs || true)

# Data processing specific env vars
PROCESSED_OUTPUT_DIR=${PROCESSED_OUTPUT_DIR}
OUTPUT_FOLDER_NAME_FOR_LABELS_DATA_SPARK_PITSIKALIS_2019=${OUTPUT_FOLDER_NAME_FOR_LABELS_DATA_SPARK_PITSIKALIS_2019}
OUTPUT_FOLDER_NAME_FOR_TRANSSHIP_AIS_DATA_SPARK_PITSIKALIS_2019=${OUTPUT_FOLDER_NAME_FOR_TRANSSHIP_AIS_DATA_SPARK_PITSIKALIS_2019}
OUTPUT_FOLDER_NAME_FOR_NON_TRANSSHIP_AIS_DATA_SPARK_PITSIKALIS_2019=${OUTPUT_FOLDER_NAME_FOR_NON_TRANSSHIP_AIS_DATA_SPARK_PITSIKALIS_2019}

# Debug logs
echo "Running as user: $(id)"

exec "$@"
