FROM python:3.8.19-slim

WORKDIR /app

COPY ./applications/model_training_api .
COPY ./domain/ ./domain/

# Install Python dependencies
RUN pip install -r ./model-training-api-requirements.txt

# Expose the port the app runs on
EXPOSE ${FLASK_MODEL_TRAINING_PORT}

CMD ["python3", "run.py"]